---
output: 
  html_document:
    toc: true
    theme: journal
---

<!-- title: "The Pandemic, Politics, and Inequality" -->
<!-- author: "Evidence in Governance and Politics (EGAP) Newtork" -->

Introduction[^1]
==
How do *political conditions* shape societal responses to the COVID-19 crisis? And how do political conditions affect the extent to which consequences have been unequally endured?  We come at these questions as a network of academics and practitioners who specialize in innovations for governance, political participation, and accountability.  As such, we also want to know, what *interventions* might improve circumstances, particularly for those marginalized or facing heightened vulnerability?

[^1]: Drafted by Cyrus Samii, Daniel Rubenson, and Max Mendez-Beck with input from Claire Adida, Natalia Bueno, Rob Blair, Ruth Canagarajah, Kim Yi Dionne, Miriam Golden, Jessica Gottlieb, Alex Hartman, Evan Lieberman, Raul Pacheco-Vega, Melina Platas, Alex Scacco, Ryan Sheely, Maarten Voors, and Rebecca Wolfe. For more on EGAP’s work, see https://egap.org/

The Evidence in Governance and Politics (EGAP) network is putting forward this concept note to propose topics for governance, politics, and accountability researchers to consider and for donors to support. The concept note focuses on addressing inequalities, marginalization, and vulnerabilities that have been created and exposed by the COVID-19 crisis.  Research should not limit attention to mitigating the harms introduced by the pandemic per se. Rather, researchers should look closely at what the COVID-19 crisis reveals more generally about societies’ abilities to respond to crises and how the needs of the least well-off are addressed. Similar dynamics may follow other external shocks such as those related to climate change.  Crises of this magnitude can be revelatory in ways that shift the “Overton window” of policies that a critical mass of citizens will support, leading to policy and social changes that address longstanding inequalities. The New Deal reforms in the United States following the Great Depression exemplify this dynamic. Or, systems in place may protect fairly evenly against losses and mostly preserve ex ante conditions. On the other hand, if the government or the private sector fail to extend protection to the poor and vulnerable, such crises can leave them substantially worse off. A research priority ought to be in understanding what contributes to the latter kind of outcome and how this might be prevented. 

Politics of Pandemic Response
==
The COVID-19 crisis reveals that there is no simple equation that tells us how a society’s income and other resources determine the toll that a collective shock will inflict on that society. Current efforts to map how political characteristics explain the effects of the COVID-19 crisis include Bosancianu et al.’s (2020) “Social and political correlates of Covid-19” project [^2] and Cheng et al.’s (2020) CoronaNet project.[^3] From these, we see that the way resources are mobilized to respond to a shock like COVID-19 depends on the conflicts and values that a society’s political system embodies and the voices that it includes or omits. This in turn determines how much people are left vulnerable to sickness, employment, and income loss, food insecurity, intimate partner violence, and other harms, and how such vulnerability is distributed societally.  

[^2]: https://wzb-ipi.github.io/corona/ and https://wzb-ipi.github.io/corona/paper.pdf

[^3]: https://www.coronanet-project.org/index.html 

Government inaction in the face of crisis leaves vulnerable those who are limited, due to poverty or exclusion, in the resources they have to protect themselves. This exposes the poor or otherwise excluded populations to larger losses. In this way, government inaction in offering safety nets can amplify existing inequalities.  A key question, then, is what conditions prevent government responsiveness to the needs of the vulnerable?

We focus here on two sets of conditions: the first is polarization and the second is corruption and elite capture. The reason to emphasize these two conditions is that there is strong observational evidence about their importance in crisis response dynamics.  In addition to that, social scientists have already begun in defining and testing intervention strategies to address them.  This is not to say that other factors are unimportant; rather that on the basis of current evidence and theory, there is good reason for minds to concentrate on these two.
 
Political scientists point to polarization, and affective polarization in particular, along partisan, racial/ethnic, or generational lines as a force that undermines collective responses to societal threats. Affective polarization refers to the extent to which citizens view themselves as separated into groups with little in common and with little affinity or trust across groups.[^4]  Sometimes these perceptions are based on erroneous assumptions about differences across groups, but even so, the force of such perceptions on intergroup behavior and emotions can be intense.[^5]

[^4]: Shanto Iyengar, Yphtach Lelkes, Matthew Levendusky, Neil Malhotra, and Sean J. Westwood (2019) "The Origins and Consequences of Affective Polarization in the United States." Annual Review of Political Science 22, 129–146. Affective polarization is distinct from notions of polarization that characterize the distribution of policy preferences, as in Morris P. Fiorina and Samuel J. Abrams (2008), “Political Polarization in the American Public,” Annual Review of Political Science 11: 563-588.

[^5]: Douglas J. Ahler and Gaurav Sood (2018), "The Parties in Our Heads: Misperceptions about Party Composition and Their Consequences," The Journal of Politics 80(3), 964-981; Jeffrey Lees and Mina Cikara (2020) "Inaccurate group meta-perceptions drive negative out-group attributions in competitive contexts," Nature Human Behavior 4, 279–286.

Polarization in these terms can make it impossible to reach broad agreement about the nature of threats, policy priorities, or even matters of scientific fact. Amidst crises more generally, Albertson and Gadarian (2015) argue that anxiety can cause people to deepen their attachment to partisan news and group leaders in their search for security, increasing polarization.[^6] In the context of the AIDS crisis, Lieberman (2009) showed how polarization in the form of exclusionary attitudes across racial and ethnic lines can cause people to cast blame and shame onto outgroups rather than viewing the crisis as something to be addressed collectively.[^7] Economic pressures can increase xenophobic sentiment and exclusion. A study by Gottlieb, Lebas, and Magat (2020) in Lagos, Nigeria found that COVID-related aid favored members of the ethnic majority, and that members of this political ingroup who were affected by the crisis also had heightened feelings of exclusion and distaste toward the outgroup.[^8] In these ways, anxiety induced by crises increases polarization, and polarization impedes a collective response by a society.

[^6]: Bethany Albertson and  Shana Kushner Gadarian. Don't Worry, Be Trusting?: The Effect of Anxiety on Political Trust. Anxious Politics. Democratic Citizenship in a Threatening World. (2015) Cambridge University Press
[^7]: Evan Lieberman, Boundaries of Contagion: How Ethnic Politics Have Shaped Government Responses to AIDS (New Jersey: Princeton University Press, 2009). For a discussion of how that argument applies to the politics of responding to COVID, see, https://items.ssrc.org/covid-19-and-the-social-sciences/democracy-and-pandemics/risk-for-us-or-for-them-the-comparative-politics-of-diversity-and-responses-to-aids-and-covid-19/
[^8]: Gottlieb, Jessica, Adrienne Lebas, and Janica Magat. "Resilience and Risk in the Informal Sector: Responses to Economic and Security Risks of COVID-19 in Lagos, Nigeria." July 2020. https://www.dropbox.com/s/qo404upjjgycb5w/Lagos%20COVID%20survey%20Wave%201%20-%20website.pdf?dl=0.

Populations may suffer unequally if corruption and government capture by elites, who are often insulated from extensive harms wrought by crises, deflect pressure for broad-based protections. Existing inequalities can also be exacerbated when crises provide new opportunities for unequal access, e.g., when crisis aid is funneled to the wealthy or well-connected. In a study of the international AIDS response “supply chain,” Dionne (2018) found that limited scrutiny by intended beneficiaries left international donors and domestic governmental elites free to divert or otherwise waste resources.[^9]

[^9]: Kim Yi Dionne, Doomed Interventions: The Failure of Global Responses to AIDS in Africa (New York: Cambridge University Press, 2018).

Such corruption contributes to public mistrust in health systems, with further perverse consequences. Morse et al. (2016) found that in the context of the Ebola crisis, distrust in government in Liberia lowered public use of health services. In the same context, Blair et al. (2017) found that citizens who expressed low trust in the government were much less likely to take precautions in their own homes or to abide by government-mandated social distancing.[^10]

[^10]: Benjamin Morse, Karen A Grépin, Robert A. Blair and Lily Tsai. Patterns of demand for non-Ebola health services during and after the Ebola outbreak: panel survey evidence from Monrovia, Liberia (2016); Robert A. Blair, Benjamin S. Morse, Lily L.Tsai. Public health and public trust: Survey evidence from the Ebola Virus Disease epidemic in Liberia. Social Science & Medicine. Volume 172, January 2017, Pages 89-97.

If governments are unwilling to offer public services, then non-governmental actors may step into the breach, sometimes productively, but typically in ways that cannot achieve the scale of government response and often in ways that lack formal accountability and that exacerbates inequalities. Examples of the role played by non-state actors in the current pandemic include news reports of criminal groups in Rio’s favelas imposing curfews and restricting tourist entry to slow the spread of the virus; gangs in Guatemala announcing a temporary suspension of extortion fees; Italian mafias and Mexican cartels delivering groceries and other basic necessities within territories they control, and Yakuza groups in Japan providing protective equipment and medical supplies.[^11]

[^11]: The Guardian (2020), "Brazil gangs impose strict curfews to slow coronavirus spread," March 25 (online edition); Silvio Barsetti (2020), "Coronavírus: Tráfico proíbe turistas em favelas do Rio," Terra (online edition), March 19; El Periodico (2020), "Pandilleros conceden indulto en el cobro de extorsión," March 20 (online edition); The Guardian (2020), "Mafia distributes food to Italy's struggling residents," April 10 (online edition); Vanda Felbab-Brown (2020), "Mexican cartels are providing COVID-19 assistance. Why that’s not surprising," Mexico Today, April 27 (online edition); Alessia Cerantola, "Japanese Gangs Vie for Power Amid Pandemic," Organized Crime and Corruption Reporting Project,  April 22 (online edition).

Points of Intervention
==
The analysis above suggests the value of strategies to either reduce polarization or neutralize its paralyzing effects. It also points to the value of strategies to increase accountability so as to limit corruption that distort crisis response and inspire mistrust among non-elites. Such interventions could mitigate the harms of the current pandemic, including the concentration of harms among the least well-off.  They could also serve as the basis of strategies to build more just and responsive systems of governance of societal shocks more generally. 

In thinking about potential interventions, a basic question is, at what level does it make sense to intervene and who is best positioned to take action? Different strategies might involve civil society, government actors, or citizens en masse. One also needs to keep in mind risks and constraints introduced by the crisis itself.

Existing literature can guide current efforts to address these questions. With regard to polarization and intergroup animosity, Siegel and Badaan (2020) show in the Middle East that elites can play an important role in mitigating the spread of harmful rhetoric, by acting as social referents that alert individuals to social norms of acceptable behavior.[^12] In the US context, Broockman and Kalla (2020) show that non-judgmentally exchanging narratives in interpersonal conversations can facilitate durable reductions in exclusionary attitudes.[^13] Mousa (2020) finds that well-structured intergroup contact between Christian and Muslim youth in Iraq in a sports league can reduce prejudice among participants, although the effects do not spillover to the broader community.[^14] Scacco and Warren (2018) find that intergroup contact between Christian and Muslim youth in Nigeria in an educational setting can reduce discriminatory behavior even if it does not reduce affective beliefs.[^15] Adida, Lo, and Platas (2018) and Simonovits, Kezdi, and Kardos (2018) find that “perspective-taking” exercises in an online setting can promote inclusiveness toward minority groups and refugees.[^16] On the basis of these results, a question that arises is whether strategies to reduce affective polarization might improve individuals’ willingness to bear or redistribute costs so as to protect the vulnerable.

[^12]: Siegel, A., & Badaan, V. (2020). #No2Sectarianism: Experimental Approaches to Reducing Sectarian Hate Speech Online. American Political Science Review, 114(3), 837-855.
[^13]: Kalla, J. L., & Broockman, D. E. (2020). Reducing exclusionary attitudes through interpersonal conversation: evidence from three field experiments. American Political Science Review, 114(2), 410-425.
[^14]: Salma Mousa (2020), "Building social cohesion between Christians and Muslims through soccer in post-ISIS Iraq," Science 369(6505):866-870.
[^15]: Alexandra Scacco and Shana Warren (2018) "Can Social Contact Reduce Prejudice and Discrimination? Evidence from a Field Experiment in Nigeria," American Political Science Review, 112(3), 654-677.
[^16]: Claire L. Adida, Adeline Lo, Melina R. Platas (2018) "Perspective taking can promote short-term inclusionary behavior toward Syrian refugees," Proceedings of the National Academy of Sciences 115(38), 9521-9526, and Gabor Simonovitz, Gabor Kezdi, and Peter Kardos (2018) "Seeing the World Through the Other's Eye: An Online Intervention Reducing Ethnic Prejudice,". American Political Science Review, 112(1), 186-193.

Overcoming the exclusionary consequences of corruption may require getting elites to view interventions as being aligned with their political incentives. Preliminary data analysis by Vavrek and Warshaw (2020) shows that (in the United States) COVID deaths affect public opinion negatively towards the political leader held responsible for directing overall policy responses.[^17] Likewise, in Europe, political leaders have been (initially) rewarded in public opinion polls for taking aggressive action in the form of lockdowns to mitigate the spread of COVID-19.[^18] These findings align with a broader literature that suggests that politicians are considered responsible for policy responses to disasters. Bringing this information to politicians could thus potentially encourage them to adopt policies that mitigate the spread of COVID-19.  In principle, there may be ways to present information to politicians and bureaucrats that will be effective in encouraging attention to the needs of the vulnerable. That said, Raffler, Posner, and Parkerson (2019) show for the health services in Uganda, seemingly promising bottom-up informational and mobilization strategies can yield disappointing effects when deployed on a mass scale.[^19] From experiments in Mexico, Peru, and the United States, Lagunes (2019) finds that corruption between the wealthy and bureaucrats can withstand strengthened top-down accountability through enhanced monitoring.[^20] Thus, the question arises as to precisely what accountability interventions might effectively induce elites to prioritize the welfare of the vulnerable in a crisis?

[^17]: Lynn Vavreck and Christopher Warshaw, “How Local Covid Deaths are Affecting Vote Choice,” The New York Times, July 18, 2020.
[^18]: Andre Blais, Damien Bol, Marco Giani, and Peter Loewen, “The effect of COVID-19 lockdowns on political support: Some good news for democracy?” Quantitative Political Economy Working Paper 2020-1, King’s College, London, April 2020. 
[^19]: Pia Raffler, Daniel N. Posner, and Doug Parkerson (2019) “The Weakness of Bottom-Up Accountability: Experimental Evidence from the Ugandan Health Sector,” working paper, Harvard University, University of California-Los Angeles, and Innovations for Poverty Action. 
[^20]: Paul Lagues (2019), The Eye and the Whip: Field Experiments on Corruption Control in the Americas, manuscript, Columbia University.

Other work has focused on strategies for overcoming public mistrust, which may stem from a history of corruption or elite capture, and may continue to undermine societal crisis response even if governance improves. In the context of the Ebola crisis in Sierra Leone, Christensen et al. (2020) found that improving the perceived quality of health services through accountability measures (both community and incentive-based) can increase clinic utilization rates, satisfaction, and even health outcomes. The study further showed that these improvements proved critical during the West Africa Ebola crisis, leading to higher reporting of cases and a significant reduction in Ebola-related deaths.[^21] Work in Liberia by Tsai et al. (2020) during the Ebola crisis shows that a government door-to-door canvassing campaign that looked to persuade residents to voluntarily comply with policies for containing the disease, was effective at increasing adherence to safety precautions and inducing support for contentious control policies. Further qualitative work on this intervention showed that local intermediaries were effective communicators because their embeddedness in communities subjected them to monitoring and sanctioning, thereby assuring their fellow residents that they were accountable and thus credible.[^22] In situations where health services are in place to address the needs of the vulnerable, can measures such as these increase uptake?

[^21]: Darin Christensen, Oeindrila Dube, Johannes Haushofer, Bilal Siddiqi, Maarten J. Voors. Building Resilient Health Systems: Experimental Evidence from Sierra Leone and the 2014 Ebola Outbreak. NBER Working Paper No. 27364
[^22]: Tsai, L. L., Morse, B. S., & Blair, R. A. (2020). Building Credibility and Cooperation in Low-Trust Settings: Persuasion and Source Accountability in Liberia During the 2014–2015 Ebola Crisis. Comparative Political Studies, 53(10–11), 1582–1618.

Conclusion
==
The COVID-19 crisis is testing the systems that societies have in place to care for the disadvantaged. In some political systems, the crisis may actually create an opportunity to address structural barriers that produce inequality. In others, however, underlying conditions like polarization or corruption may result in government policy neglecting the needs of the disadvantaged.  This concept note has outlined what recent research in political science suggests as reasons for such negative dynamics to take hold and points of potential intervention to mitigate them.  On the basis of this analysis, EGAP intends to support researchers, particularly those based in the Global South and those addressing the conditions of disadvantaged communities around the world.  For more information on EGAP’s efforts in this regard, please visit https://egap.org.
